name: Purge Cache

on:
  check_run:
    types: [completed]

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
